### ISSUE TITLE
Difference between `Lazy` and `asio::awaitable` or `asio::experimental::coro` ?

### ISSUE THREAD

**Issue by PragmaTwice** [alibaba/async_simple#95]
### What happened
It is well known that asio provides several ways to perform io operations, i.e. synchronous, asynchronous by callback or (chained) future, asynchronous by stackful coroutines (with boost::coroutine2 or boost::fiber) and asynchronous by stackless coroutines (with `asio::awaitable` or the newer `asio::experimental::coro` for c++20 coroutines).
So I just wonder the relationship between `Lazy` provided by this library and them, especially what advantages does this library have over those boost things?

(difference between `asio::awaitable` and `asio::experimental::coro`: the former is literally just awaitable, while the latter can be an async generator.)

**Comment by qicosmos** [comment]
@PragmaTwice 
I think asio::awaitable or asio::experimental::coro is similar with async_simple Lazy in syntax, represent a lazy task, however i think there are some differences:
the target is different, async_simple is more general, it can be used with any async library not only asio, it can also used with libaio etc, however asio::awaitable is more special, it work with asio async interface very well but not so general.
history: async_simple was developed since 2019, no any industry stackless coroutine library at all at that time, async_simple is developed for Alibaba's requirements.

**Comment by ChuanqiXu9** [comment]
@PragmaTwice 
> So I just wonder the relationship between Lazy provided by this library and them, especially what advantages does this library have over those boost things?

It is natural to wonder so since the whole usage looks similar. In fact, not only async_simple::Lazy and asio::await able looks similar. Also folly::Task and cppcoro::task looks similar too. The reason is that all of them share the same semantic model, an asynchronous task. And I am not sure what is the oldest implementation : ) Historically, when we implement async_simple::Lazy, we looks at the implementation from folly::Task. But we don't look at the asio::awaitable that time.

So here is the first answer for the question:
> What's the relationship between async_simple::Lazy  and asio::awaitable?

They implement the same model so they looks similar.

Your second question is:
> what advantages does this library have over those boost things?

I would like to use the word 'differences' over 'advantages': )

For asio::awaitable, I know it appeared very early when there is no standard C++ coroutine. Although asio::awaitable adds supports for c++ stackless coroutine later to allow the user to `co_await` it. It must take the previous burden.

For asio::experimental::coro, it has more semantics than an asynchronous task. As you said, it is possible to make asio::experimental::coro a generator but it is impossible for async_simple::Lazy. On the other side, the more flexible the class is, it is harder for user to use it. As far as we know, asio::experimental::coro is still in experimental namespace and we could image it need to be wrapped to be ready to be used. 

From the perspective of implementation, async_simple::Lazy fits more for the compiler optimization. For example, to enable an optimization called Coroutine Elision (which could convert dynamic allocation to a stack allocation), the coroutine class should only contain one data member refer to the coroutine handle. This is what async_simple::Lazy does and asio::experimental::coro didn't. You could find the information about coroutine elision at:  http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0981r0.html

Hope this helps.
